### ISSUE TITLE
Rework state machine

### ISSUE THREAD

**Issue by VictorKoenders** [EspressoSystems/HotShot#120]
# General flow 

- [ ] #141 
- [ ]  #142 

# TODOs
- [ ] Replace specialized QC types with generic
  - [ ] Rename Prepare
  - [ ] New view needs to be combined with vote
- [ ] Fee distribution policy #138 
- [ ] Validate the implementation based on [the spec](https://arxiv.org/pdf/1803.05069.pdf)
  - [ ]  Recommended: refer to the paper in the algorithm
- [ ] Add a list of `Transaction` IDs to each `Prepare` so the nodes agree on what is being voted on. #136
