### ISSUE TITLE
[parent] Light client integration 

### ISSUE THREAD

**Issue by alxiong** [EspressoSystems/HotShot#1986]
1. APIs
    1. Fetching states and schnorr signatures from DA nodes
        1. Consensus states
        2. Schnorr signatures
        3. Do we have the corresponding DA interfaces?
        4. Prover also needs to store the stake table (from L1) for checking DA nodes’ Schnorr signatures
    2. Proof generation
    3. Submit proofs to the contract
2. Deployment (ask Mat)

## Tasks

Dependency for stake table
- [ ] https://github.com/EspressoSystems/espresso-sequencer/issues/737
- [ ] https://github.com/EspressoSystems/espresso-sequencer/issues/761

Dependency for schnorr signature logic
- [x] #2090 
- [x] #2021 
- [ ] https://github.com/EspressoSystems/hotshot-query-service/issues/248

Prover service implementation
- [x] #1987
- [x] #1988 

_caution: this description might go outdated from time to time, when in doubt, refer to [notion page](https://www.notion.so/espressosys/Light-Client-Contract-a416ebbfa9f342d79fccbf90de9706ef#0c04e8dca0d14ba4a6c8da8c25b5cbec)_

**Comment by philippecamacho** [comment]
> High Uncertainty: fallback + robustness (malicious withholding leader etc)

 Idea: the replicas monitor the lightclient contract and delete their Schnorr signatures once the contract is up to date. Honest leaders monitor the lightclient contract as well and call the replicas/ state prover service as needed until catchup is achieved.

**Comment by alxiong** [comment]
Sorry, that was outdated description, I copied the notion section over. @philippecamacho 

We don't have to deal with garbage collection in our work
