### ISSUE TITLE
[Macro] Push CDN

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2312]
### What is this task and why do we need to work on it?

This macro task references the Push CDN and all associated work.
We need the push-based CDN to reduce latency and add horizontal scalability of the CDN.

### What work will need to be done to complete this task?

- [x] Finish diagram (https://github.com/EspressoSystems/HotShot/issues/2313)
- [x] Finish / write-up diagram explanation (https://github.com/EspressoSystems/HotShot/issues/2314)
- [x] Lower-level write-ups for common implementation questions and edge cases (https://github.com/EspressoSystems/HotShot/issues/2315)
- [x] Describe broker interface API. Used for both broker <-> broker comms and user <-> broker comms (https://github.com/EspressoSystems/HotShot/issues/2316)
- [x] PoC
    - [x] Peer discovery (https://github.com/EspressoSystems/HotShot/issues/2317)
    - [x] Topic subscriptions (https://github.com/EspressoSystems/HotShot/issues/2318)
- [x] Integrate with HotShot
    - [x] Message serialization (https://github.com/EspressoSystems/HotShot/issues/2319)
    - [x] Implement ConnectedNetwork (https://github.com/EspressoSystems/HotShot/issues/2320)
    - [x] Use it in a test (https://github.com/EspressoSystems/HotShot/issues/2321)
- [x] CRDTs for state changes (https://github.com/EspressoSystems/Push-CDN/issues/7)
- [x] Write some basic tests for it (https://github.com/EspressoSystems/HotShot/issues/2324)
- [x] https://github.com/EspressoSystems/Push-CDN/issues/11
- [x] https://github.com/EspressoSystems/Push-CDN/issues/10
- [x] https://github.com/EspressoSystems/Push-CDN/issues/12
- [x] Benchmark PoC (https://github.com/EspressoSystems/HotShot/issues/2322)
- [x] Tune/debug PoC based on benchmarks (https://github.com/EspressoSystems/HotShot/issues/2323)
- [x] https://github.com/EspressoSystems/Push-CDN/issues/9

### What are the acceptance criteria to close this issue?

The PoC push CDN is implemented, tested, and benchmarked.
