### ISSUE TITLE
[Auto Benchmarks] Add more benchmark stats

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#2341]
### What is this task and why do we need to work on it?

We want to add more stats for benchmarks: things like minimum and maximum view latencies. The exact metrics will be defined in a discussion that is yet to be had. It will allow us to get more detailed benchmarking data.

### What work will need to be done to complete this task?

Child tasks:
- [x] Define which stats we want #2343 
- [x] Implement those new stats #2345
- [x] Update the orchestrator to collect more stats #2346

### What are the acceptance criteria to close this issue?

At the end, we should have 
1. New stats
2. A way to send those stats to the orchestrator
