### ISSUE TITLE
HotShot open sourcing checklist

### ISSUE THREAD

**Issue by VictorKoenders** [EspressoSystems/HotShot#254]
At the time of staging deployment, we should check off anything in the release checklist that is unlikely to change between staging and release and that doesn't relate directly to releasing code publicly (e.g. open sourcing related tasks are not included here).

- [x]  All tests pass
- [x]  Check all README.md are up to date
- [x]  README has instructions on how to set up development environment
- [x]  README has instructions on how to run tests
- [x]  ~Instructions for obtaining help are included in all reasonable starting points, e.g. all the README.md files~ (not relevant for staging as we will not have any users, no support channels to point to)
- [ ]  All TODO comments are clear, actionable, and linked to a GitHub issue (See below)
- [x] Rename the project and repository to `hotshot` #282
- [ ] Licenses in all projects

(Based on https://github.com/EspressoSystems/espresso/issues/132)

Upcoming changes we want to merge in before 0.1.0:

- [ ] ~~VRF ~~
- [ ] ~~Nathan Y's untangle (maybe)~~
- [x] #282
- [x]  #277 
- [x] #278
