### ISSUE TITLE
[MACRO] Libp2p upgrade

### ISSUE THREAD

**Issue by rob-maron** [EspressoSystems/HotShot#3193]
### What is this task and why do we need to work on it?

This is the macro task for upgrading a live network to add peer-to-peer functionality.

### What work will need to be done to complete this 

**Subtasks**:

@rob-maron 
- [x] [Deploy a `CombinedNetwork` environment in staging](https://github.com/EspressoSystems/HotShot/issues/3194)
  - [x] [Test the CDN crashing](https://github.com/EspressoSystems/HotShot/issues/3195)
  - [x] [Restart tests - test bootstrapping capabilities](https://github.com/EspressoSystems/HotShot/issues/3196)

- [x] [Come up with a way to configure Libp2p bootstrapping without the orchestrator](https://github.com/EspressoSystems/HotShot/issues/3197)
  - [x] [Implement the above](https://github.com/EspressoSystems/HotShot/issues/3198)

@lukaszrzasik 
- [ ] [Tune delays and timeouts](https://github.com/EspressoSystems/HotShot/issues/3199)
- [ ] [Optimistically calculate VID when the CDN is down](https://github.com/EspressoSystems/HotShot/issues/3028)
- [ ] [Delay sending of `ResponseMessage::NotFound`](https://github.com/EspressoSystems/HotShot/issues/3046)
- [ ] [Long Running Tests with Libp2p](https://github.com/EspressoSystems/HotShot/issues/2537)

### What are the acceptance criteria to close this issue?

All subtasks are closed
